id: 96069c34a5934af5a06c7501030ab11b
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_249-The_Sutra_Teaching_the_Four_Factors-v2
  language: bo
  author: ''
  volume: {}
